FROM azul/zulu-openjdk-alpine:21
ENV DATASOURCE_URL DATASOURCE_URL
ENV DATASOURCE_USERNAME DATASOURCE_USERNAME
ENV DATASOURCE_PASSWORD DATASOURCE_PASSWORD
ENV AWS_ENDPOINT AWS_ENDPOINT
ENV AWS_SQS_ENDPOINT_ENVIA_EMAILS AWS_SQS_ENDPOINT_ENVIA_EMAILS
ENV AWS_CLIENT_ID AWS_CLIENT_ID
ENV AWS_SECRET_ID AWS_SECRET_ID
ENV API_CLIENTE_ENDPOINT API_CLIENTE_ENDPOINT
ENV AWS_SQS_ENDPOINT_PROCESSA_PEDIDOS AWS_SQS_ENDPOINT_PROCESSA_PEDIDOS
ENV API_PRODUTO_ENDPOINT API_PRODUTO_ENDPOINT
ENV AWS_REGION AWS_REGION
EXPOSE 8083
COPY target/*.jar pedidos-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/pedidos-0.0.1-SNAPSHOT.jar"]
